language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pip install codecov
  - coverage run -m unittest discover -s ./test
  - coverage report -m
  - codecov --token=948898dc-2ad8-4221-8e76-402cdf6c1e26
